DBSettings:
  dbHost: "127.0.0.1"
  dbPort: "5432"
  dbName: "postgres"
  dbUsername: "postgres"
  dbPassword: "pass"

ProgramSettings:
  host: "localhost"
  port: ":7328"
  logPath: "./logs/backend"
